### PR TITLE
Implement federate_thread_TCP

### PR DESCRIPTION
**Pull request by chanijjani**
- Add handle_timestamp
- Add struct StartTime to handle start_time in tag.c
- Add struct MessageRecord to cover message_record.c
- Add condition variable to handle lf_cond_wait
- Add handle_next_event_tag
- Add handle_stop_request_message
- Add handle_timed_message
- Add handle_federate_resign
- Add handle_stop_request_reply
- Add handle_port_absent_message

### CODE REVIEW

**Comment by chanijjani** [comment]
Implemented handle_stop_request_message function incompletely due to a bug but proceeded to handle_logical_tag_complete() implementation to save time.

**Comment by chanijjani** [comment]
Finish  handle_stop_request_message() implementation.

**Comment by chanijjani** [comment]
2818 line

**Review by hokeun — APPROVED** [review]
Very nice!!

**Pull request merged**
